"""Build a SHA-pinned, self-contained single-file R14 certificate verifier."""
from proof_guard import require
import base64
import hashlib
import io
import json
from pathlib import Path
import textwrap
import zipfile


ROOT=Path(__file__).resolve().parent
SCRIPTS=[
    'ANALYTIC_PROOF.md',
    'build_standalone_r14.py',
    'proof_guard.py',
    'verify_r14_package.py',
    'exact_finite_r4.py',
    'exact_finite_rank2.py',
    'verify_factor_dirichlet_rank2.py',
    'verify_source_tail_rank2.py',
    'verify_finite_block_rank2.py',
    'far_schur_bound_rank2.py',
    'aggregate_schur_rank2.py',
    'cert_near_schur_rank2.py',
    'bound_finite_cross_source_rank2.py',
    'cert_finite_cross_shape_rank2.py',
    'aggregate_finite_cross_shape_rank2.py',
    'cert_H_near_rank2.py',
    'aggregate_H_rank2.py',
    'bound_QD_source_rank2.py',
    'bound_preconditioner_norm_r14.py',
    'bound_high_source_defect_r14.py',
    'bound_high_shape_defect_r14.py',
    'aggregate_finite_input_coarse_r14.py',
    'cert_finite_input_coarse_rank2.py',
    'verify_last_finite_column_r14.py',
    'nonlinear_majorant_rank2.py',
    'verify_center_shift_r14.py',
    'verify_radii_geometry_r14.py',
    'verify_center_geometry_sign_rank2.py',
]
DATA=[
    'center_r14_M114_S36_arbrefined.json',
    'center_r14_M186_S48_arbrefined2.json',
    'Ahat_r14_M114_S36.npy',
    'r14_M114_finite_inverse_profile.json',
    'r14_M114_schur_far.json',
    'r14_M114_lastshape_tail_seed.json',
    'r14_M114_nonlinear_bounds.json',
    'r14_M186_nonlinear_bounds.json',
]
PATTERNS={
    'r14_M114_jac_*.json':8,
    'r14_M114_schur_[0-9]*.json':4,
    'r14_M114_cross_shape_*.json':11,
    'r14_M114_H_*.json':4,
    'r14_M114_finite_coarse_*.json':8,
}


def main():
    names=list(SCRIPTS)+list(DATA)
    for pattern,count in PATTERNS.items():
        found=sorted(p.name for p in ROOT.glob(pattern))
        require((len(found)==count), (pattern,len(found)))
        names.extend(found)
    require((len(names)==len(set(names))), 'build_standalone_r14.py:67: proof gate failed')
    manifest=dict(kind='R14_CERTIFICATE_V2',
                  files={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest()
                         for name in sorted(names)})
    manifest_name='CERTIFICATE_MANIFEST_R14.json'
    (ROOT/manifest_name).write_text(json.dumps(manifest,sort_keys=True,
                                              separators=(',',':'))+'\n')
    names.append(manifest_name)
    buf=io.BytesIO()
    with zipfile.ZipFile(buf,'w',compression=zipfile.ZIP_DEFLATED,compresslevel=9) as z:
        for name in sorted(names):
            z.write(ROOT/name,arcname=name)
    payload=buf.getvalue()
    digest=hashlib.sha256(payload).hexdigest()
    encoded=base64.b85encode(payload).decode('ascii')
    lines='\n'.join('    '+repr(part) for part in textwrap.wrap(encoded,100))
    source=f'''#!/usr/bin/env python3
"""Self-contained R14 Berenstein certificate verifier.

Generated by build_standalone_r14.py. The payload SHA256 and every included
file SHA256 are checked before the inequalities in Sections 6 and 7.
Use --recompute-all to regenerate every bounded column certificate.
"""
import base64
import hashlib
import io
import os
from pathlib import Path, PurePosixPath
import subprocess
import sys
import tempfile
import zipfile

PAYLOAD_SHA256={digest!r}
PAYLOAD=(
{lines}
)

def main():
    if not __debug__:
        raise SystemExit('optimized Python disables proof assertions')
    raw=base64.b85decode(PAYLOAD.encode('ascii'))
    if hashlib.sha256(raw).hexdigest()!=PAYLOAD_SHA256:
        raise SystemExit('payload SHA256 mismatch')
    with tempfile.TemporaryDirectory(prefix='r14_certificate_') as folder:
        root=Path(folder)
        with zipfile.ZipFile(io.BytesIO(raw)) as z:
            for info in z.infolist():
                path=PurePosixPath(info.filename)
                if path.is_absolute() or len(path.parts)!=1 or path.name in ('.','..'):
                    raise SystemExit('unsafe payload path')
                (root/path.name).write_bytes(z.read(info))
        env=os.environ.copy()
        env.update(OMP_NUM_THREADS='1',OPENBLAS_NUM_THREADS='1',MKL_NUM_THREADS='1')
        p=subprocess.run([sys.executable,'-B','verify_r14_package.py',*sys.argv[1:]],
                         cwd=root,env=env,check=False,preexec_fn=lambda:os.nice(19))
        raise SystemExit(p.returncode)

if __name__=='__main__':
    main()
'''
    out=ROOT/'verify_r14.py'
    out.write_text(source)
    print('built',out.name,'embedded files',len(names),
          'payload bytes',len(payload),'standalone bytes',out.stat().st_size,
          'payload SHA256',digest,
          'standalone SHA256',hashlib.sha256(out.read_bytes()).hexdigest())


if __name__=='__main__':
    main()
